name: Tests

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tests:
    name: Conan build
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        config:
          - { cc: "gcc", cxx: "g++" }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up pipx
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath

      - name: Set up Conan
        run: |
          pipx install conan

      - name: Install compilers
        run: |
          sudo apt-get install ninja-build
          ./scripts/install_deps_ubuntu.sh --dev

      - name: Restore build caches
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}

      - name: Build sc-machine with tests
        id: run_cmake
        run: |
          cmake --preset=release-with-tests-conan
          cmake --build --preset release

      - name: Run sc-machine tests
        id: run_tests
        run: cd build && ctest -C Debug -V

      - name: Run sc-machine
        id: run_sc_machine
        run: |
          mkdir kb
          build/Release/bin/sc-builder -i kb -o kb.bin --clear -f
          build/Release/bin/sc-server -t -c sc-machine.ini -r kb.bin
          build/Release/bin/sc-machine -t -c sc-machine.ini -r kb.bin
