name: Docker

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ostis/sc-machine:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Docker Compose
        run: docker-compose up -d --wait
