name: Tests

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tests:
    name: ${{ matrix.os }}, ${{ matrix.build_type }}, ${{ matrix.config.cxx }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        build_type: ["Debug", "Release"]
        config:
          - { cc: "gcc", cxx: "g++" }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          scripts/install_dependencies.sh --dev

      - name: Restore build caches
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.config.cxx }}-${{ matrix.build_type }}

      - name: Build
        id: run_cmake
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
          BUILD_TYPE: ${{ matrix.build_type }}
          COVERAGE: OFF
          SANITIZER_TYPE: none
        run: scripts/build_sc_machine.sh -t

      - name: Run tests
        id: run_tests
        run: scripts/run_tests.sh

      - name: Run sc-machine
        id: run_sc_machine
        run: |
          mkdir kb
          build/bin/sc-builder -i kb -o kb.bin --clear
          build/bin/sc-machine -t -c sc-machine.ini -s kb.bin
