name: Sanitizers

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_sanitizers:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Sanitizer - address",
            os: ubuntu-24.04,
            sanitizer: "address",
            cc: clang,
            cxx: clang++,
          }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: apt cache
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/
            /var/lib/apt/
          key: apt-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/install_deps_ubuntu.sh') }}

      - name: Install dependencies
        id: install_deps
        run: scripts/install_deps_ubuntu.sh --dev

      - name: Restore build caches
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.config.os}}-${{ matrix.config.cxx }}-${{ matrix.config.build_type }}

      - name: Build
        id: run_cmake
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
          BUILD_TYPE: ${{ matrix.config.build_type }}
          COVERAGE: OFF
          SANITIZER_TYPE: ${{ matrix.config.sanitizer }}
        run: cmake --preset debug -DSC_USE_SANITIZER=${{ matrix.config.sanitizer }} && cmake --build --preset debug

      - name: Run tests
        id: run_tests
        run: cd build/Debug && ctest -C Debug -V
